### ISSUE TITLE
images are not showing up in the readme file

### ISSUE THREAD

**Issue by prajwalrajup** [prajwalraju/Service-Management#2]

**Comment by vishalsingh2972** [comment]
@prajwalraju  could you assign this to me and send the images that need to be added?

**Comment by prajwalrajup** [comment]
@vishalsingh2972 Thank you for your help.
The images are uploaded in the `/assets` location, and the file names should be in the readme file itself.

**Comment by vishalsingh2972** [comment]
@prajwalraju done images are showIng now, could you please check and approve PR https://github.com/prajwalraju/Service-Management/pull/3

**Comment by prajwalrajup** [comment]
@vishalsingh2972 approved the PR, Thank you.
